language: ruby
rvm:
  - 2.1.2

gemfile:
  - Gemfile

env:
- DB=mysql

before_script:
  - RAILS_ENV=test bundle exec rake db:create
  - RAILS_ENV=test bundle exec rake db:migrate

script:
  - RAILS_ENV=test bundle exec rake rspec
